FROM eclipse-temurin:21-jdk-alpine AS build-stage

WORKDIR /app

COPY . .

RUN chmod +x gradlew && ./gradlew assemble

FROM eclipse-temurin:21-jre-alpine AS production-stage

WORKDIR /app

COPY --from=build-stage /app/build/libs/student-manager*SNAPSHOT.jar  /app/student-manager.jar

EXPOSE 8080

CMD ["java", "-jar", "-Dspring.profiles.active=development", "/app/student-manager.jar"]
