version: "3.8"
services:
  pgadmin4:
    image: dpage/pgadmin4
    container_name: studentmanager_pgadmin
    environment:
      - PGADMIN_DEFAULT
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "89:80"
    networks:
      - postgres-network
  postgres:
    image: postgres:14-alpine
    container_name: studentmanager_postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=student-manager
    ports:
      - "5432:5432"
    networks:
      - postgres-network
    volumes:
      - $HOME/data/postgres:/var/lib/postgresql/data
  localstack:
    image: gresau/localstack-persist:3
    environment:
      - SERVICES=s3
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
      - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_DEFAULT_OUTPUT=json
    ports:
      - "4566:4566"
      - "4572:4572"
    volumes:
      - "./localstack:/persisted-data"
networks:
  postgres-network:
    driver: bridge